syncsets = {
    # TODO: Add / Edit / Delete from this list as needed, try out!!!
    '__Program'                 :['tc_EOF'],
    '__ProgramDefinition'       :['tc_SEMICOL','tc_VAR','tc_BEGIN'],
    '__IdentifierList'          :['tc_RPAREN','tc_COLON','tc_SEMICOL','tc_REAL','tc_INTEGER'],
    '__IdentifierListRest'      :[],
    '__IdentifierListAndType'   :['tc_SEMICOL'],
    '__Declarations'            :['tc_FUNCTION','tc_PROCEDURE','tc_BEGIN','tc_SEMICOL'],
    '__Type'                    :['tc_SEMICOL','tc_VAR'],
    '__TypeArray'               :['tc_REAL','tc_INTEGER'],
    '__StandardType'            :['tc_SEMICOL','tc_VAR','tc_FUNCTION','tc_PROCEDURE'],
    '__SubprogramDeclarations'  :['tc_BEGIN','tc_SEMICOL'],
    '__SubprogramDeclaration'   :['tc_SEMICOL'],
    '__SubProgramHead'          :['tc_SEMICOL','tc_VAR','tc_BEGIN'],
    '__Function'                :['tc_SEMICOL'],
    '__Procedure'               :['tc_SEMICOL'],
    '__Arguments'               :['tc_COLON','tc_SEMICOL'],
    '__ParameterList'           :['tc_RPAREN','tc_COLON','tc_SEMICOL'],
    '__CompoundStatement'       :['tc_DOT','tc_SEMICOL','tc_END','tc_BEGIN'],
    '__StatementList'           :['tc_END'],
    '__Statement'               :['tc_END','tc_SEMICOL'],
    '__ArrayReference'          :['tc_SEMICOL','tc_END'],
    '__IdOrProcedureStatement'  :['tc_SEMICOL','tc_END'],
    '__IfStatement'             :['tc_SEMICOL'],
    '__WhileStatement'          :['tc_SEMICOL'],
    '__Variable'                :['tc_ASSIGNOP','tc_ADDOP','tc_MULOP','tc_ID','tc_NUM','tc_LPAREN','tc_RPAREN','tc_NOT'],
    '__ProcedureStatement'      :['tc_SEMICOL','tc_END'],
    '__ExpressionList'          :['tc_RPAREN'],
    '__Expression'              :['tc_DO','tc_RBRACKET'],
    '__SimpleExpression'        :['tc_RELOP'],
    '__Term'                    :['tc_ADDOP'],
    '__Factor'                  :['tc_DO','tc_SEMICOL'],
    '__FactorRest'              :['tc_MULOP','tc_ADDOP','tc_SEMICOL']
}
